set Echo=off
echo -- Quick Help --
echo
echo Type `mm` to enter file manager.
echo Type `sr` to enter SofaRun.
echo Type `basic` to enter BASIC interpreter and `call system` to go back to DOS.
echo
echo Type this to run a rom file:
echo      romload a:\roms\kmarescc.rom
echo      reset
echo
echo For disk images, go to dsk folder and type either:
echo      cd dsk
echo      ep gradius.dsk b:      to mount as drive b:
echo      ep gradius.dsk /b /r   to mount and run from disk
echo
echo Search for files with:
echo      dir a:\roms\*.rom
echo
